export const ApiConfig = {
  auth: {
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
  },
  empresas: {
    list: '/api/empresas',
    byId: (id: number) => `/api/empresas/${id}`,
    activar: (id: number) => `/api/empresas/${id}/activar`,
    desactivar: (id: number) => `/api/empresas/${id}/desactivar`,
    restaurar: (id: number) => `/api/empresas/${id}/restaurar`,
  },
  sucursales: {
    list: '/api/sucursales',
    byId: (id: number) => `/api/sucursales/${id}`,
    byEmpresa: (empresaId: number) => `/api/sucursales/empresa/${empresaId}`,
    activar: (id: number) => `/api/sucursales/${id}/activar`,
    desactivar: (id: number) => `/api/sucursales/${id}/desactivar`,
    restaurar: (id: number) => `/api/sucursales/${id}/restaurar`,
  },
  camaras: {
    list: '/api/camaras',
    byId: (id: number) => `/api/camaras/${id}`,
    bySucursal: (sucursalId: number) => `/api/camaras/sucursal/${sucursalId}`,
    activar: (id: number) => `/api/camaras/${id}/activar`,
    desactivar: (id: number) => `/api/camaras/${id}/desactivar`,
    restaurar: (id: number) => `/api/camaras/${id}/restaurar`,
    temperatura: (id: number) => `/api/camaras/${id}/temperatura`,
    ultimasLecturas: (id: number) => `/api/camaras/${id}/ultimas-lecturas`,
    lecturas: (id: number) => `/api/camaras/${id}/lecturas`,
  },
  sensores: {
    list: '/api/sensores',
    registrar: '/api/sensores/registrar',
    asignar: '/api/sensores/asignar',
    byCamara: (camaraId: number) => `/api/sensores/camara/${camaraId}`,
    byUuid: (uuid: string) => `/api/sensores/${uuid}`,
    estado: (uuid: string) => `/api/sensores/${uuid}/estado`,
    renewApiKey: (uuid: string) => `/api/sensores/${uuid}/renew-api-key`,
    restaurar: (uuid: string) => `/api/sensores/${uuid}/restaurar`,
  },
  lecturas: {
    porSensor: (uuid: string) => `/api/lecturas/sensor/${uuid}`,
  },
  usuarios: {
    list: '/api/usuarios',
    byId: (id: number) => `/api/usuarios/${id}`,
    byEmpresa: (empresaId: number) => `/api/usuarios/empresa/${empresaId}`,
    bySucursal: (sucursalId: number) => `/api/usuarios/sucursal/${sucursalId}`,
    password: (id: number) => `/api/usuarios/${id}/password`,
    activar: (id: number) => `/api/usuarios/${id}/activar`,
    desactivar: (id: number) => `/api/usuarios/${id}/desactivar`,
    restaurar: (id: number) => `/api/usuarios/${id}/restaurar`,
  },
}
